language: cpp

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit2.0
    - LUA=luajit2.1

branches:
  only:
    - master

before_install:
  # Install Lua and setup env.
  - source .travis/setenv_lua.sh
  # Install testing dependency
  - sudo luarocks install busted
  - sudo luarocks install dromozoa-utf8

install:
  - sudo luarocks make

# Run tests
script:
  - busted

notifications:
  email:
    on_success: change
    on_failure: always
